---

# To download any yum dependency

- name: Dependancies_To_Perform_SpeedTest
  yum:
    name:
      - python
      - wget
  tags: three

# To download file from a specified link 

- name: SPEED_TEST_PROCESS_2
  get_url:
    url: http://www.speedtest.net/speedtest-servers.php
    dest: /root/
    mode: 0777
  tags:
   - five

# Line_in_file is used to replace a single line/word

- name: DISABLE_SELINUX
  lineinfile:
    path: /etc/selinux/config
    regexp: "{{ item.regexp}}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: '^enforcing', line: 'disabled' }
    - { regexp: '^permissive', line: 'disabled' }

# To restart a service

- name: restart sshd service
  service:
    name: sshd
    state: restarted

# To update the machine to it's latest version

- name: Update the machine
  yum: name=* state=latest

# To install development tools

- name: install the 'Development tools' package group
  yum:
    name: "@Development tools"
    state: present

# To install RPM package manager

- name: RPM install and build files
  yum:
    name: http://dl.fedoraproject.org/pub/epel/7/x86_64/Packages/e/epel-release-7-11.noarch.rpm
    state: present

